export const TitlePath = {
  report: "",
  settingEachBranch: "ตั้งค่าหน่วยงานภายใต้คณะ",
  settingMyBranch: "ตั้งค่าระบบ",
  slideShow: "รูปภาพหน้าเว็บ",
  news: "ข่าวประชาสัมพันธ์",
  personnel: "บุคลากร",
  student: "นักศึกษา",
  role: "บทบาท",
  prefix: "คำนำหน้าชื่อ",
  position: "ตำแหน่ง",
  generalPosition: "ตำแหน่งทั่วไป",
  research_and_project: "โครงงานวิจัยอาจารย์",
  project: "งานวิจัยนักศึกษา",
  courseSpecification: "มคอ.",
  jobHistory: "ประวัติการทำงานของนักศึกษา",
  annualDirector: "ชุดคณะกรรมการ",
  director: "กรรมการ",
  section: "ปรัชญา วิสัยทัศน์ พันธกิจ",
  weLearn: "เรียนอะไรบ้าง?",
  curriculum: "หลักสูตร",
};
